# Generated by Django 2.1.1 on 2018-09-16 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0013_auto_20180914_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reade_Num',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_num', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterModelOptions(
            name='article',
            options={},
        ),
        migrations.RemoveField(
            model_name='article',
            name='reader_num',
        ),
        migrations.AddField(
            model_name='reade_num',
            name='article',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='article.Article'),
        ),
    ]
