# Generated by Django 2.1.1 on 2018-09-16 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0014_auto_20180916_1421'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reade_Num',
            new_name='Read_Num',
        ),
    ]
