# Generated by Django 2.1.1 on 2018-09-16 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0015_auto_20180916_1431'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Read_Num',
            new_name='ReadNum',
        ),
    ]
